// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW3NDK3KbGx6SUJJwm6k1RticmIlfpDJE',
    appId: '1:228261720777:web:a188b6cb4914d933239318',
    messagingSenderId: '228261720777',
    projectId: 'clasemoviles-2025-2',
    authDomain: 'clasemoviles-2025-2.firebaseapp.com',
    storageBucket: 'clasemoviles-2025-2.firebasestorage.app',
    measurementId: 'G-8HLGDKHREP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTyAAImkYgn2Pfg6BvMO1A0uNmXSHPHQ',
    appId: '1:228261720777:android:8892c38a4a0f3856239318',
    messagingSenderId: '228261720777',
    projectId: 'clasemoviles-2025-2',
    storageBucket: 'clasemoviles-2025-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPjWTQr5Xw5Y1Tm-7D9x-8oNJa_ge9cE',
    appId: '1:228261720777:ios:0f76a16e5fdb3c7e239318',
    messagingSenderId: '228261720777',
    projectId: 'clasemoviles-2025-2',
    storageBucket: 'clasemoviles-2025-2.firebasestorage.app',
    iosBundleId: 'com.example.talleres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPPjWTQr5Xw5Y1Tm-7D9x-8oNJa_ge9cE',
    appId: '1:228261720777:ios:0f76a16e5fdb3c7e239318',
    messagingSenderId: '228261720777',
    projectId: 'clasemoviles-2025-2',
    storageBucket: 'clasemoviles-2025-2.firebasestorage.app',
    iosBundleId: 'com.example.talleres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW3NDK3KbGx6SUJJwm6k1RticmIlfpDJE',
    appId: '1:228261720777:web:e18295e7d3aaf835239318',
    messagingSenderId: '228261720777',
    projectId: 'clasemoviles-2025-2',
    authDomain: 'clasemoviles-2025-2.firebaseapp.com',
    storageBucket: 'clasemoviles-2025-2.firebasestorage.app',
    measurementId: 'G-2H5SNN76GR',
  );
}
